name: publish
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set Git user
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/github-script@v5
        with:
          script: console.log(context)
      - name: Set variables
        id: vars
        run: |
          echo ::set-output name=lernaVersion::"$(jq -r .version lerna.json)"
          echo ::set-output name=lastMinor::"$((npm --silent info @fbtmp/lerna01-pkg01 version || echo '0.0.0') | sed 's/[0-9]*\.\([0-9]*\).*/\1/')"
          echo "TAG=v0.5.0" >> $GITHUB_ENV
      - if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        run: echo "On the default branch"
      - if: github.ref != format('refs/heads/{0}', github.event.repository.default_branch)
        run: echo "Not on the default branch"
      - name: Release minor
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        run: |
          git checkout -b v0.$((MINOR+1))
          git push -u origin v0.$((MINOR+1))
          yarn --frozen-lockfile
          yarn lerna publish 0.$((MINOR+1)).0 --yes --exact --force-publish --no-verify-access
        env:
          MINOR: ${{ steps.vars.outputs.lastMinor }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Release patch
        if: startsWith(steps.vars.outputs.lernaVersion, '0.')
        run: |
          git checkout ${GITHUB_REF#refs/heads/}
          yarn --frozen-lockfile
          yarn lerna publish patch --yes --exact --force-publish --no-verify-access
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: git push --all --follow-tags
      - name: Create Release Notes
        uses: actions/github-script@v5
        with:
          script: |
            await github.request(`POST /repos/${{ github.repository }}/releases`, {
              draft: true,
              generate_release_notes: true,
              tag_name: "${{ env.TAG }}"
            });
